# Generated by Django 3.0.2 on 2020-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default=None),
        ),
    ]
